name: Python Markdown Documentation
description: Creates markdown files based on python docstrings
inputs:
  src_path:
    description: "Path to the source folder containing python code"
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.src_path }}
